version: '3.1'

services:
  frontend:
    build: 
      context: . 
      args:
        # change the password and use the same custom password here and below
        mysqlpw: pleasechangeme
    #Uncomment this line if you want to always restart the service when your machine/docker host starts
    #restart: always
    ports:
      - 8085:8085
    # Forward requests to this port (localhost:8085)
    expose:
      - "8085"
    depends_on:
      - db
    container_name: csbar_frontend
  db:
    image: mysql
    #Uncomment this line if you want to always restart the service when your machine/docker host starts
    #restart: always
    command: --default-authentication-plugin=mysql_native_password
    #./.data/db will be the folder where your database persists, even if you restart the containers.
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      # change the password and use the same custom password here and above
      MYSQL_ROOT_PASSWORD: pleasechangeme
      MYSQL_DATABASE: CSBarDB
    ports:
      - 42333:3306
    # You may want to use this if you would like direct remote access to the db container from outside the container network
    #expose: 
    #  - "3306"
    container_name: csbar_backend
  adminer:
    image: adminer
    #Uncomment this line if you want to always restart the service when your machine/docker host starts
    #restart: always
    ports:
      - 8080:8080
    container_name: csbar_backend_admin_interface